package com.zycj.business.park.dto;

import java.util.Date;

public class TradeAttr {
	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_attr.id
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_attr.pay_type
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_attr.trade_no
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_attr.attr_cd1
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    private String attrCd1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_attr.attr_cd2
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    private String attrCd2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_attr.attr_value
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    private String attrValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_attr.created_time
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    private Date createdTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_attr.id
     *
     * @return the value of trade_attr.id
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_attr.id
     *
     * @param id the value for trade_attr.id
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_attr.pay_type
     *
     * @return the value of trade_attr.pay_type
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_attr.pay_type
     *
     * @param payType the value for trade_attr.pay_type
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_attr.trade_no
     *
     * @return the value of trade_attr.trade_no
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_attr.trade_no
     *
     * @param tradeNo the value for trade_attr.trade_no
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo == null ? null : tradeNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_attr.attr_cd1
     *
     * @return the value of trade_attr.attr_cd1
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public String getAttrCd1() {
        return attrCd1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_attr.attr_cd1
     *
     * @param attrCd1 the value for trade_attr.attr_cd1
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public void setAttrCd1(String attrCd1) {
        this.attrCd1 = attrCd1 == null ? null : attrCd1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_attr.attr_cd2
     *
     * @return the value of trade_attr.attr_cd2
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public String getAttrCd2() {
        return attrCd2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_attr.attr_cd2
     *
     * @param attrCd2 the value for trade_attr.attr_cd2
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public void setAttrCd2(String attrCd2) {
        this.attrCd2 = attrCd2 == null ? null : attrCd2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_attr.attr_value
     *
     * @return the value of trade_attr.attr_value
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_attr.attr_value
     *
     * @param attrValue the value for trade_attr.attr_value
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue == null ? null : attrValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_attr.created_time
     *
     * @return the value of trade_attr.created_time
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_attr.created_time
     *
     * @param createdTime the value for trade_attr.created_time
     *
     * @mbggenerated Wed Apr 08 14:44:27 CST 2015
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }
}
