server:
    port: 9090
    session:
        timeout: 1800
    tomcat:
        uri-encoding: UTF-8 # Tomcat编码
        compression: on # Tomcat是否开启压缩，默认为关闭（TODO 未验证）


spring:
    application:
        name: hfzycj.com

    jpa:
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: none

    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://localhost:5432/hfzycj_com
#        url: jdbc:postgresql://10.91.83.16:2345/hfzycj_com
        username: hfzycj_com
        password: hfzycj_com
        type: com.alibaba.druid.pool.DruidDataSource
        initialSize: 50 # 初始化大小
        minIdle: 10 # 最小
        maxActive: 100 # 最大
        maxWait: 60000 # 获取连接等待超时的时间，单位：毫秒
        timeBetweenEvictionRunsMillis: 60000 # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位：毫秒
        minEvictableIdleTimeMillis: 300000 # 一个连接在池中最小生存的时间，单位：毫秒
        validationQuery: SELECT 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
        maxPoolPreparedStatementPerConnectionSize: 20
        # filters: stat,wall,slf4j # 监控统计拦截的filters，去掉后监控界面sql无法统计，wall用于防火墙


    freemarker:
        suffix: .html
        cache: false
        charset: UTF-8
        allowRequestOverride: false
        allowSessionOverride: false
        checkTemplateLocation: false
        contentType: text/html
        exposeRequestAttributes: true # 设定所有request的属性在merge到模板的时候，是否要都添加到model中
        exposeSessionAttributes: false # 设定所有HttpSession的属性在merge到模板的时候，是否要都添加到model中
        templateEncoding: UTF-8
        settings:
            template_update_delay: 0
            default_encoding: UTF-8
            classic_compatible: true
            locale: zh_CN
            date_format: yyyy-MM-dd
            time_format: HH:mm:ss
            datetime_format: yyyy-MM-dd HH:mm:ss
            auto_import: spring.ftl as s


    devtools:
        restart:
            additional-paths: target/classes/

#    http:
#        multipart:
#            location: /Users/young/upload/hfzycj/
#            location: /home/file/hfzycj/
#            max-file-size: 10MB
#            max-request-size: 100MB # 每次请求的最大值
#            max-file-size: -1 # 文件不受限制

upload:
    path: /Users/young/upload/hfzycj/
#    path: /home/file/hfzycj/
