package com.zycj.tcc.dao;

import com.zycj.tcc.domain.LogSystem;
import com.zycj.tcc.domain.LogSystemExample;
import com.zycj.tcc.domain.criteria.LogSystemCriteria;
import com.zycj.tcc.domain.vo.LogSystemVo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface LogSystemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_system
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int countByExample(LogSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_system
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_system
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insert(LogSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_system
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insertSelective(LogSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_system
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    List<LogSystem> selectByExample(LogSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_system
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    LogSystem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_system
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") LogSystem record, @Param("example") LogSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_system
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExample(@Param("record") LogSystem record, @Param("example") LogSystemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_system
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKeySelective(LogSystem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log_system
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKey(LogSystem record);
    
    /**
     * 按条件查询
     * @param criteria
     * @return
     */
    List<LogSystemVo> list(LogSystemCriteria criteria);
    /**
     * 按条件查询记录数
     * @param criteria
     * @return
     */
    int count(LogSystemCriteria criteria);
}