package com.zycj.tcc.dao;

import com.zycj.tcc.domain.NewsDetail;
import com.zycj.tcc.domain.NewsDetailExample;
import com.zycj.tcc.domain.criteria.NewsDetailCriteria;
import com.zycj.tcc.domain.vo.NewsDetailVo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface NewsDetailMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	int countByExample(NewsDetailExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	int insert(NewsDetail record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	int insertSelective(NewsDetail record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	List<NewsDetail> selectByExampleWithBLOBs(NewsDetailExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	List<NewsDetail> selectByExample(NewsDetailExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	NewsDetail selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	int updateByExampleSelective(@Param("record") NewsDetail record,
			@Param("example") NewsDetailExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") NewsDetail record,
			@Param("example") NewsDetailExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	int updateByExample(@Param("record") NewsDetail record,
			@Param("example") NewsDetailExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	int updateByPrimaryKeySelective(NewsDetail record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(NewsDetail record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	int updateByPrimaryKey(NewsDetail record);
	/**
     * 按条件查�?
     * @param criteria
     * @return
     */
    List<NewsDetailVo> list(NewsDetailCriteria criteria);
    /**
     * 按条件查询记录数
     * @param criteria
     * @return
     */
    int count(NewsDetailCriteria criteria);
}