package com.zycj.tcc.dao;

import com.zycj.tcc.domain.RechargeOrder;
import com.zycj.tcc.domain.RechargeOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RechargeOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int countByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insert(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insertSelective(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    List<RechargeOrder> selectByExample(RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    RechargeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") RechargeOrder record, @Param("example") RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExample(@Param("record") RechargeOrder record, @Param("example") RechargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKeySelective(RechargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recharge_order
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKey(RechargeOrder record);
}