package com.zycj.tcc.dao;

import com.zycj.tcc.domain.SysAdminRole;
import com.zycj.tcc.domain.SysAdminRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysAdminRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int countByExample(SysAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insert(SysAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insertSelective(SysAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    List<SysAdminRole> selectByExample(SysAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    SysAdminRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysAdminRole record, @Param("example") SysAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExample(@Param("record") SysAdminRole record, @Param("example") SysAdminRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKeySelective(SysAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKey(SysAdminRole record);
    /**
     * 删除admin Id分配的所有角色
     * @param adminId
     * @return
     */
    int deleteByAdminId(Integer adminId);
}