package com.zycj.tcc.dao;

import com.zycj.tcc.domain.SysAdmin;
import com.zycj.tcc.domain.SysAdminExample;
import com.zycj.tcc.domain.criteria.SysAdminCriteria;
import com.zycj.tcc.domain.vo.SysAdminVo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface SysAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int countByExample(SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insert(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insertSelective(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    List<SysAdmin> selectByExample(SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    SysAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysAdmin record, @Param("example") SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExample(@Param("record") SysAdmin record, @Param("example") SysAdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKeySelective(SysAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKey(SysAdmin record);
    /**
     * 根据登录名，获取登录信息
     * @param loginName
     * @return
     */
    SysAdminVo getSysAdminByLoginName(String loginName);
    
    /**
     * 按条件查询
     * @param criteria
     * @return
     */
    List<SysAdminVo> list(SysAdminCriteria criteria);
    /**
     * 按条件查询记录数
     * @param criteria
     * @return
     */
    int count(SysAdminCriteria criteria);
    /**
     * 包含自增的id
     * @param record
     * @return
     */
     int insertWithId(SysAdmin record);
     /**
      * 根据admin Id 获取分配的 roleId拼接的字符串
      */
     String getRoleIdsByAdminId(Integer adminId);
     
     /**
      * 根据admin id 获取SysAdminVo
      */
     SysAdminVo getSysAdminById(Integer id);
}