package com.zycj.tcc.dao;

import com.zycj.tcc.domain.UserBocardDetail;
import com.zycj.tcc.domain.UserBocardDetailExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserBocardDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bocard_detail
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int countByExample(UserBocardDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bocard_detail
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bocard_detail
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insert(UserBocardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bocard_detail
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insertSelective(UserBocardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bocard_detail
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    List<UserBocardDetail> selectByExample(UserBocardDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bocard_detail
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    UserBocardDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bocard_detail
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserBocardDetail record, @Param("example") UserBocardDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bocard_detail
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExample(@Param("record") UserBocardDetail record, @Param("example") UserBocardDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bocard_detail
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKeySelective(UserBocardDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_bocard_detail
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKey(UserBocardDetail record);
}