package com.zycj.tcc.dao;

import com.zycj.tcc.domain.User;
import com.zycj.tcc.domain.UserFeedback;
import com.zycj.tcc.domain.UserFeedbackExample;
import com.zycj.tcc.domain.criteria.UserFeedbackCriteria;
import com.zycj.tcc.domain.vo.UserFeedbackVo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserFeedbackMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int countByExample(UserFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insert(UserFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int insertSelective(UserFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    List<UserFeedback> selectByExample(UserFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    UserFeedback selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") UserFeedback record, @Param("example") UserFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByExample(@Param("record") UserFeedback record, @Param("example") UserFeedbackExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKeySelective(UserFeedback record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_feedback
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    int updateByPrimaryKey(UserFeedback record);
    
    int updateByPrimaryKey(User record);
	/**
     * 按条件查
     * @param criteria
     * @return
     */
    List<UserFeedbackVo> list(UserFeedbackCriteria criteria);
    /**
     * 按条件查询记录数
     * @param criteria
     * @return
     */
    int count(UserFeedbackCriteria criteria);
}