package com.zycj.tcc.dao;

import com.zycj.tcc.domain.User;
import com.zycj.tcc.domain.UserExample;
import com.zycj.tcc.domain.criteria.UserCriteria;
import com.zycj.tcc.domain.vo.UserVo;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	int countByExample(UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	int insert(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	int insertSelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	List<User> selectByExample(UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	User selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	int updateByExampleSelective(@Param("record") User record,
			@Param("example") UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	int updateByExample(@Param("record") User record,
			@Param("example") UserExample example);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	int updateByPrimaryKeySelective(User record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table user
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	int updateByPrimaryKey(User record);
	/**
     * 按条件查
     * @param criteria
     * @return
     */
    List<UserVo> list(UserCriteria criteria);
    /**
     * 按条件查询记录数
     * @param criteria
     * @return
     */
    int count(UserCriteria criteria);
}