package com.zycj.tcc.domain;

import java.util.Date;

public class LogSystem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_system.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_system.operator_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String operatorName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_system.operator_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_system.operate_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_system.value_before
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String valueBefore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_system.value_after
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String valueAfter;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_system.operate_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date operateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_system.ip
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_system.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log_system.update_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_system.id
     *
     * @return the value of log_system.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_system.id
     *
     * @param id the value for log_system.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_system.operator_name
     *
     * @return the value of log_system.operator_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_system.operator_name
     *
     * @param operatorName the value for log_system.operator_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_system.operator_id
     *
     * @return the value of log_system.operator_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_system.operator_id
     *
     * @param operatorId the value for log_system.operator_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setOperatorId(Integer operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_system.operate_type
     *
     * @return the value of log_system.operate_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_system.operate_type
     *
     * @param operateType the value for log_system.operate_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setOperateType(Integer operateType) {
        this.operateType = operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_system.value_before
     *
     * @return the value of log_system.value_before
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getValueBefore() {
        return valueBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_system.value_before
     *
     * @param valueBefore the value for log_system.value_before
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setValueBefore(String valueBefore) {
        this.valueBefore = valueBefore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_system.value_after
     *
     * @return the value of log_system.value_after
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getValueAfter() {
        return valueAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_system.value_after
     *
     * @param valueAfter the value for log_system.value_after
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setValueAfter(String valueAfter) {
        this.valueAfter = valueAfter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_system.operate_time
     *
     * @return the value of log_system.operate_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getOperateTime() {
        return operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_system.operate_time
     *
     * @param operateTime the value for log_system.operate_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setOperateTime(Date operateTime) {
        this.operateTime = operateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_system.ip
     *
     * @return the value of log_system.ip
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_system.ip
     *
     * @param ip the value for log_system.ip
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_system.create_time
     *
     * @return the value of log_system.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_system.create_time
     *
     * @param createTime the value for log_system.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log_system.update_time
     *
     * @return the value of log_system.update_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log_system.update_time
     *
     * @param updateTime the value for log_system.update_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}