package com.zycj.tcc.domain;

import java.util.Date;

public class NewsDetail {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.id
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.title
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.img_url
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private String imgUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.brief
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private String brief;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.detail_url
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private String detailUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.up_time
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private Date upTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.status
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.news_from
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private String newsFrom;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.type
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private Integer type;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.create_time
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.modify_time
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private Date modifyTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column news_detail.content
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	private String content;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.id
	 * @return  the value of news_detail.id
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.id
	 * @param id  the value for news_detail.id
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.title
	 * @return  the value of news_detail.title
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.title
	 * @param title  the value for news_detail.title
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.img_url
	 * @return  the value of news_detail.img_url
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public String getImgUrl() {
		return imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.img_url
	 * @param imgUrl  the value for news_detail.img_url
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setImgUrl(String imgUrl) {
		this.imgUrl = imgUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.brief
	 * @return  the value of news_detail.brief
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public String getBrief() {
		return brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.brief
	 * @param brief  the value for news_detail.brief
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setBrief(String brief) {
		this.brief = brief;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.detail_url
	 * @return  the value of news_detail.detail_url
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public String getDetailUrl() {
		return detailUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.detail_url
	 * @param detailUrl  the value for news_detail.detail_url
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setDetailUrl(String detailUrl) {
		this.detailUrl = detailUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.up_time
	 * @return  the value of news_detail.up_time
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public Date getUpTime() {
		return upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.up_time
	 * @param upTime  the value for news_detail.up_time
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setUpTime(Date upTime) {
		this.upTime = upTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.status
	 * @return  the value of news_detail.status
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.status
	 * @param status  the value for news_detail.status
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.news_from
	 * @return  the value of news_detail.news_from
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public String getNewsFrom() {
		return newsFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.news_from
	 * @param newsFrom  the value for news_detail.news_from
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setNewsFrom(String newsFrom) {
		this.newsFrom = newsFrom;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.type
	 * @return  the value of news_detail.type
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public Integer getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.type
	 * @param type  the value for news_detail.type
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setType(Integer type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.create_time
	 * @return  the value of news_detail.create_time
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.create_time
	 * @param createTime  the value for news_detail.create_time
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.modify_time
	 * @return  the value of news_detail.modify_time
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.modify_time
	 * @param modifyTime  the value for news_detail.modify_time
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column news_detail.content
	 * @return  the value of news_detail.content
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column news_detail.content
	 * @param content  the value for news_detail.content
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setContent(String content) {
		this.content = content;
	}

	@Override
	public String toString() {
		return "NewsDetail [id=" + id + ", title=" + title + ", imgUrl="
				+ imgUrl + ", brief=" + brief + ", detailUrl=" + detailUrl
				+ ", upTime=" + upTime + ", status=" + status + ", newsFrom="
				+ newsFrom + ", type=" + type + ", createTime=" + createTime
				+ ", modifyTime=" + modifyTime + ", content=" + content + "]";
	}
	
	
}