package com.zycj.tcc.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class NewsDetailExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public NewsDetailExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value,
				String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1,
				Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property
						+ " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("NDL.id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("NDL.id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Integer value) {
			addCriterion("NDL.id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("NDL.id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("NDL.id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("NDL.id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Integer value) {
			addCriterion("NDL.id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("NDL.id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Integer> values) {
			addCriterion("NDL.id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Integer> values) {
			addCriterion("NDL.id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("NDL.id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("NDL.id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andTitleIsNull() {
			addCriterion("NDL.title is null");
			return (Criteria) this;
		}

		public Criteria andTitleIsNotNull() {
			addCriterion("NDL.title is not null");
			return (Criteria) this;
		}

		public Criteria andTitleEqualTo(String value) {
			addCriterion("NDL.title =", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotEqualTo(String value) {
			addCriterion("NDL.title <>", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThan(String value) {
			addCriterion("NDL.title >", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleGreaterThanOrEqualTo(String value) {
			addCriterion("NDL.title >=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThan(String value) {
			addCriterion("NDL.title <", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLessThanOrEqualTo(String value) {
			addCriterion("NDL.title <=", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleLike(String value) {
			addCriterion("NDL.title like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotLike(String value) {
			addCriterion("NDL.title not like", value, "title");
			return (Criteria) this;
		}

		public Criteria andTitleIn(List<String> values) {
			addCriterion("NDL.title in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotIn(List<String> values) {
			addCriterion("NDL.title not in", values, "title");
			return (Criteria) this;
		}

		public Criteria andTitleBetween(String value1, String value2) {
			addCriterion("NDL.title between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andTitleNotBetween(String value1, String value2) {
			addCriterion("NDL.title not between", value1, value2, "title");
			return (Criteria) this;
		}

		public Criteria andImgUrlIsNull() {
			addCriterion("NDL.img_url is null");
			return (Criteria) this;
		}

		public Criteria andImgUrlIsNotNull() {
			addCriterion("NDL.img_url is not null");
			return (Criteria) this;
		}

		public Criteria andImgUrlEqualTo(String value) {
			addCriterion("NDL.img_url =", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlNotEqualTo(String value) {
			addCriterion("NDL.img_url <>", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlGreaterThan(String value) {
			addCriterion("NDL.img_url >", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlGreaterThanOrEqualTo(String value) {
			addCriterion("NDL.img_url >=", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlLessThan(String value) {
			addCriterion("NDL.img_url <", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlLessThanOrEqualTo(String value) {
			addCriterion("NDL.img_url <=", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlLike(String value) {
			addCriterion("NDL.img_url like", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlNotLike(String value) {
			addCriterion("NDL.img_url not like", value, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlIn(List<String> values) {
			addCriterion("NDL.img_url in", values, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlNotIn(List<String> values) {
			addCriterion("NDL.img_url not in", values, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlBetween(String value1, String value2) {
			addCriterion("NDL.img_url between", value1, value2, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andImgUrlNotBetween(String value1, String value2) {
			addCriterion("NDL.img_url not between", value1, value2, "imgUrl");
			return (Criteria) this;
		}

		public Criteria andBriefIsNull() {
			addCriterion("NDL.brief is null");
			return (Criteria) this;
		}

		public Criteria andBriefIsNotNull() {
			addCriterion("NDL.brief is not null");
			return (Criteria) this;
		}

		public Criteria andBriefEqualTo(String value) {
			addCriterion("NDL.brief =", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotEqualTo(String value) {
			addCriterion("NDL.brief <>", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefGreaterThan(String value) {
			addCriterion("NDL.brief >", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefGreaterThanOrEqualTo(String value) {
			addCriterion("NDL.brief >=", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefLessThan(String value) {
			addCriterion("NDL.brief <", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefLessThanOrEqualTo(String value) {
			addCriterion("NDL.brief <=", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefLike(String value) {
			addCriterion("NDL.brief like", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotLike(String value) {
			addCriterion("NDL.brief not like", value, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefIn(List<String> values) {
			addCriterion("NDL.brief in", values, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotIn(List<String> values) {
			addCriterion("NDL.brief not in", values, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefBetween(String value1, String value2) {
			addCriterion("NDL.brief between", value1, value2, "brief");
			return (Criteria) this;
		}

		public Criteria andBriefNotBetween(String value1, String value2) {
			addCriterion("NDL.brief not between", value1, value2, "brief");
			return (Criteria) this;
		}

		public Criteria andDetailUrlIsNull() {
			addCriterion("NDL.detail_url is null");
			return (Criteria) this;
		}

		public Criteria andDetailUrlIsNotNull() {
			addCriterion("NDL.detail_url is not null");
			return (Criteria) this;
		}

		public Criteria andDetailUrlEqualTo(String value) {
			addCriterion("NDL.detail_url =", value, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlNotEqualTo(String value) {
			addCriterion("NDL.detail_url <>", value, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlGreaterThan(String value) {
			addCriterion("NDL.detail_url >", value, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlGreaterThanOrEqualTo(String value) {
			addCriterion("NDL.detail_url >=", value, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlLessThan(String value) {
			addCriterion("NDL.detail_url <", value, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlLessThanOrEqualTo(String value) {
			addCriterion("NDL.detail_url <=", value, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlLike(String value) {
			addCriterion("NDL.detail_url like", value, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlNotLike(String value) {
			addCriterion("NDL.detail_url not like", value, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlIn(List<String> values) {
			addCriterion("NDL.detail_url in", values, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlNotIn(List<String> values) {
			addCriterion("NDL.detail_url not in", values, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlBetween(String value1, String value2) {
			addCriterion("NDL.detail_url between", value1, value2, "detailUrl");
			return (Criteria) this;
		}

		public Criteria andDetailUrlNotBetween(String value1, String value2) {
			addCriterion("NDL.detail_url not between", value1, value2,
					"detailUrl");
			return (Criteria) this;
		}

		public Criteria andUpTimeIsNull() {
			addCriterion("NDL.up_time is null");
			return (Criteria) this;
		}

		public Criteria andUpTimeIsNotNull() {
			addCriterion("NDL.up_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpTimeEqualTo(Date value) {
			addCriterion("NDL.up_time =", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeNotEqualTo(Date value) {
			addCriterion("NDL.up_time <>", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeGreaterThan(Date value) {
			addCriterion("NDL.up_time >", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("NDL.up_time >=", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeLessThan(Date value) {
			addCriterion("NDL.up_time <", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeLessThanOrEqualTo(Date value) {
			addCriterion("NDL.up_time <=", value, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeIn(List<Date> values) {
			addCriterion("NDL.up_time in", values, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeNotIn(List<Date> values) {
			addCriterion("NDL.up_time not in", values, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeBetween(Date value1, Date value2) {
			addCriterion("NDL.up_time between", value1, value2, "upTime");
			return (Criteria) this;
		}

		public Criteria andUpTimeNotBetween(Date value1, Date value2) {
			addCriterion("NDL.up_time not between", value1, value2, "upTime");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("NDL.status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("NDL.status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("NDL.status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("NDL.status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("NDL.status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("NDL.status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("NDL.status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("NDL.status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("NDL.status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("NDL.status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("NDL.status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("NDL.status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andNewsFromIsNull() {
			addCriterion("NDL.news_from is null");
			return (Criteria) this;
		}

		public Criteria andNewsFromIsNotNull() {
			addCriterion("NDL.news_from is not null");
			return (Criteria) this;
		}

		public Criteria andNewsFromEqualTo(String value) {
			addCriterion("NDL.news_from =", value, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromNotEqualTo(String value) {
			addCriterion("NDL.news_from <>", value, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromGreaterThan(String value) {
			addCriterion("NDL.news_from >", value, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromGreaterThanOrEqualTo(String value) {
			addCriterion("NDL.news_from >=", value, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromLessThan(String value) {
			addCriterion("NDL.news_from <", value, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromLessThanOrEqualTo(String value) {
			addCriterion("NDL.news_from <=", value, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromLike(String value) {
			addCriterion("NDL.news_from like", value, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromNotLike(String value) {
			addCriterion("NDL.news_from not like", value, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromIn(List<String> values) {
			addCriterion("NDL.news_from in", values, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromNotIn(List<String> values) {
			addCriterion("NDL.news_from not in", values, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromBetween(String value1, String value2) {
			addCriterion("NDL.news_from between", value1, value2, "newsFrom");
			return (Criteria) this;
		}

		public Criteria andNewsFromNotBetween(String value1, String value2) {
			addCriterion("NDL.news_from not between", value1, value2,
					"newsFrom");
			return (Criteria) this;
		}

		public Criteria andTypeIsNull() {
			addCriterion("NDL.type is null");
			return (Criteria) this;
		}

		public Criteria andTypeIsNotNull() {
			addCriterion("NDL.type is not null");
			return (Criteria) this;
		}

		public Criteria andTypeEqualTo(Integer value) {
			addCriterion("NDL.type =", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotEqualTo(Integer value) {
			addCriterion("NDL.type <>", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThan(Integer value) {
			addCriterion("NDL.type >", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("NDL.type >=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThan(Integer value) {
			addCriterion("NDL.type <", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeLessThanOrEqualTo(Integer value) {
			addCriterion("NDL.type <=", value, "type");
			return (Criteria) this;
		}

		public Criteria andTypeIn(List<Integer> values) {
			addCriterion("NDL.type in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotIn(List<Integer> values) {
			addCriterion("NDL.type not in", values, "type");
			return (Criteria) this;
		}

		public Criteria andTypeBetween(Integer value1, Integer value2) {
			addCriterion("NDL.type between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("NDL.type not between", value1, value2, "type");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("NDL.create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("NDL.create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("NDL.create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("NDL.create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("NDL.create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("NDL.create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("NDL.create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("NDL.create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("NDL.create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("NDL.create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("NDL.create_time between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("NDL.create_time not between", value1, value2,
					"createTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNull() {
			addCriterion("NDL.modify_time is null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIsNotNull() {
			addCriterion("NDL.modify_time is not null");
			return (Criteria) this;
		}

		public Criteria andModifyTimeEqualTo(Date value) {
			addCriterion("NDL.modify_time =", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotEqualTo(Date value) {
			addCriterion("NDL.modify_time <>", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThan(Date value) {
			addCriterion("NDL.modify_time >", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("NDL.modify_time >=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThan(Date value) {
			addCriterion("NDL.modify_time <", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeLessThanOrEqualTo(Date value) {
			addCriterion("NDL.modify_time <=", value, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeIn(List<Date> values) {
			addCriterion("NDL.modify_time in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotIn(List<Date> values) {
			addCriterion("NDL.modify_time not in", values, "modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeBetween(Date value1, Date value2) {
			addCriterion("NDL.modify_time between", value1, value2,
					"modifyTime");
			return (Criteria) this;
		}

		public Criteria andModifyTimeNotBetween(Date value1, Date value2) {
			addCriterion("NDL.modify_time not between", value1, value2,
					"modifyTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table news_detail
	 * @mbggenerated  Thu Apr 09 10:26:54 CST 2015
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue,
				String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table news_detail
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 25 11:35:19 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}