package com.zycj.tcc.domain;

import java.math.BigDecimal;
import java.util.Date;

public class RechargeOrder {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.bis_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer bisType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.card_no
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String cardNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.pay_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.trade_no
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String tradeNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.bis_status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer bisStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.subject
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String subject;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.body
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.total_fee
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private BigDecimal totalFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.finish_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date finishTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.modify_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.notify_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date notifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.payment_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date paymentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.notify_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String notifyType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.notify_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String notifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.trade_status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String tradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.buyer_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String buyerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recharge_order.buyer_email
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String buyerEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.id
     *
     * @return the value of recharge_order.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.id
     *
     * @param id the value for recharge_order.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.bis_type
     *
     * @return the value of recharge_order.bis_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getBisType() {
        return bisType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.bis_type
     *
     * @param bisType the value for recharge_order.bis_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setBisType(Integer bisType) {
        this.bisType = bisType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.card_no
     *
     * @return the value of recharge_order.card_no
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getCardNo() {
        return cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.card_no
     *
     * @param cardNo the value for recharge_order.card_no
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.pay_type
     *
     * @return the value of recharge_order.pay_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.pay_type
     *
     * @param payType the value for recharge_order.pay_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.trade_no
     *
     * @return the value of recharge_order.trade_no
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getTradeNo() {
        return tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.trade_no
     *
     * @param tradeNo the value for recharge_order.trade_no
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setTradeNo(String tradeNo) {
        this.tradeNo = tradeNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.bis_status
     *
     * @return the value of recharge_order.bis_status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getBisStatus() {
        return bisStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.bis_status
     *
     * @param bisStatus the value for recharge_order.bis_status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setBisStatus(Integer bisStatus) {
        this.bisStatus = bisStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.subject
     *
     * @return the value of recharge_order.subject
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.subject
     *
     * @param subject the value for recharge_order.subject
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setSubject(String subject) {
        this.subject = subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.body
     *
     * @return the value of recharge_order.body
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.body
     *
     * @param body the value for recharge_order.body
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.total_fee
     *
     * @return the value of recharge_order.total_fee
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public BigDecimal getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.total_fee
     *
     * @param totalFee the value for recharge_order.total_fee
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setTotalFee(BigDecimal totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.finish_time
     *
     * @return the value of recharge_order.finish_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getFinishTime() {
        return finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.finish_time
     *
     * @param finishTime the value for recharge_order.finish_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setFinishTime(Date finishTime) {
        this.finishTime = finishTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.create_time
     *
     * @return the value of recharge_order.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.create_time
     *
     * @param createTime the value for recharge_order.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.modify_time
     *
     * @return the value of recharge_order.modify_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.modify_time
     *
     * @param modifyTime the value for recharge_order.modify_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.notify_time
     *
     * @return the value of recharge_order.notify_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getNotifyTime() {
        return notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.notify_time
     *
     * @param notifyTime the value for recharge_order.notify_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setNotifyTime(Date notifyTime) {
        this.notifyTime = notifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.payment_time
     *
     * @return the value of recharge_order.payment_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getPaymentTime() {
        return paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.payment_time
     *
     * @param paymentTime the value for recharge_order.payment_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setPaymentTime(Date paymentTime) {
        this.paymentTime = paymentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.notify_type
     *
     * @return the value of recharge_order.notify_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getNotifyType() {
        return notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.notify_type
     *
     * @param notifyType the value for recharge_order.notify_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setNotifyType(String notifyType) {
        this.notifyType = notifyType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.notify_id
     *
     * @return the value of recharge_order.notify_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getNotifyId() {
        return notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.notify_id
     *
     * @param notifyId the value for recharge_order.notify_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setNotifyId(String notifyId) {
        this.notifyId = notifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.trade_status
     *
     * @return the value of recharge_order.trade_status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getTradeStatus() {
        return tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.trade_status
     *
     * @param tradeStatus the value for recharge_order.trade_status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setTradeStatus(String tradeStatus) {
        this.tradeStatus = tradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.buyer_id
     *
     * @return the value of recharge_order.buyer_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.buyer_id
     *
     * @param buyerId the value for recharge_order.buyer_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setBuyerId(String buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recharge_order.buyer_email
     *
     * @return the value of recharge_order.buyer_email
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getBuyerEmail() {
        return buyerEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recharge_order.buyer_email
     *
     * @param buyerEmail the value for recharge_order.buyer_email
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setBuyerEmail(String buyerEmail) {
        this.buyerEmail = buyerEmail;
    }
}