package com.zycj.tcc.domain;

public class SysAdminRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_role.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_role.admin_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer adminId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_role.role_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer roleId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_role.id
     *
     * @return the value of sys_admin_role.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_role.id
     *
     * @param id the value for sys_admin_role.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_role.admin_id
     *
     * @return the value of sys_admin_role.admin_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_role.admin_id
     *
     * @param adminId the value for sys_admin_role.admin_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_role.role_id
     *
     * @return the value of sys_admin_role.role_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_role.role_id
     *
     * @param roleId the value for sys_admin_role.role_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }
}