package com.zycj.tcc.domain;

import java.util.Date;

public class SysAdmin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.login_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.login_pwd
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String loginPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.admin_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String adminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.contact
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.certificate_no
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String certificateNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.certificate_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer certificateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.update_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.login_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.last_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date lastTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin.login_total
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer loginTotal;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.id
     *
     * @return the value of sys_admin.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.id
     *
     * @param id the value for sys_admin.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.status
     *
     * @return the value of sys_admin.status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.status
     *
     * @param status the value for sys_admin.status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.login_name
     *
     * @return the value of sys_admin.login_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.login_name
     *
     * @param loginName the value for sys_admin.login_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.login_pwd
     *
     * @return the value of sys_admin.login_pwd
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getLoginPwd() {
        return loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.login_pwd
     *
     * @param loginPwd the value for sys_admin.login_pwd
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.admin_name
     *
     * @return the value of sys_admin.admin_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getAdminName() {
        return adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.admin_name
     *
     * @param adminName the value for sys_admin.admin_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setAdminName(String adminName) {
        this.adminName = adminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.contact
     *
     * @return the value of sys_admin.contact
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.contact
     *
     * @param contact the value for sys_admin.contact
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.certificate_no
     *
     * @return the value of sys_admin.certificate_no
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getCertificateNo() {
        return certificateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.certificate_no
     *
     * @param certificateNo the value for sys_admin.certificate_no
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setCertificateNo(String certificateNo) {
        this.certificateNo = certificateNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.certificate_type
     *
     * @return the value of sys_admin.certificate_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.certificate_type
     *
     * @param certificateType the value for sys_admin.certificate_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setCertificateType(Integer certificateType) {
        this.certificateType = certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.create_time
     *
     * @return the value of sys_admin.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.create_time
     *
     * @param createTime the value for sys_admin.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.update_time
     *
     * @return the value of sys_admin.update_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.update_time
     *
     * @param updateTime the value for sys_admin.update_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.login_time
     *
     * @return the value of sys_admin.login_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.login_time
     *
     * @param loginTime the value for sys_admin.login_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.last_time
     *
     * @return the value of sys_admin.last_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getLastTime() {
        return lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.last_time
     *
     * @param lastTime the value for sys_admin.last_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setLastTime(Date lastTime) {
        this.lastTime = lastTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin.login_total
     *
     * @return the value of sys_admin.login_total
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getLoginTotal() {
        return loginTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin.login_total
     *
     * @param loginTotal the value for sys_admin.login_total
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setLoginTotal(Integer loginTotal) {
        this.loginTotal = loginTotal;
    }

	@Override
	public String toString() {
		return "SysAdmin [id=" + id + ", status=" + status + ", loginName="
				+ loginName + ", loginPwd=" + loginPwd + ", adminName="
				+ adminName + ", contact=" + contact + ", certificateNo="
				+ certificateNo + ", certificateType=" + certificateType
				+ ", createTime=" + createTime + ", updateTime=" + updateTime
				+ ", loginTime=" + loginTime + ", lastTime=" + lastTime
				+ ", loginTotal=" + loginTotal + "]";
	}
    
}