package com.zycj.tcc.domain;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysPermissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public SysPermissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("SPN.id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("SPN.id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("SPN.id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("SPN.id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("SPN.id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SPN.id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("SPN.id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("SPN.id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("SPN.id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("SPN.id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("SPN.id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SPN.id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("SPN.parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("SPN.parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Integer value) {
            addCriterion("SPN.parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Integer value) {
            addCriterion("SPN.parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Integer value) {
            addCriterion("SPN.parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("SPN.parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Integer value) {
            addCriterion("SPN.parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Integer value) {
            addCriterion("SPN.parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Integer> values) {
            addCriterion("SPN.parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Integer> values) {
            addCriterion("SPN.parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Integer value1, Integer value2) {
            addCriterion("SPN.parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Integer value1, Integer value2) {
            addCriterion("SPN.parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andPerNameIsNull() {
            addCriterion("SPN.per_name is null");
            return (Criteria) this;
        }

        public Criteria andPerNameIsNotNull() {
            addCriterion("SPN.per_name is not null");
            return (Criteria) this;
        }

        public Criteria andPerNameEqualTo(String value) {
            addCriterion("SPN.per_name =", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameNotEqualTo(String value) {
            addCriterion("SPN.per_name <>", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameGreaterThan(String value) {
            addCriterion("SPN.per_name >", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameGreaterThanOrEqualTo(String value) {
            addCriterion("SPN.per_name >=", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameLessThan(String value) {
            addCriterion("SPN.per_name <", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameLessThanOrEqualTo(String value) {
            addCriterion("SPN.per_name <=", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameLike(String value) {
            addCriterion("SPN.per_name like", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameNotLike(String value) {
            addCriterion("SPN.per_name not like", value, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameIn(List<String> values) {
            addCriterion("SPN.per_name in", values, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameNotIn(List<String> values) {
            addCriterion("SPN.per_name not in", values, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameBetween(String value1, String value2) {
            addCriterion("SPN.per_name between", value1, value2, "perName");
            return (Criteria) this;
        }

        public Criteria andPerNameNotBetween(String value1, String value2) {
            addCriterion("SPN.per_name not between", value1, value2, "perName");
            return (Criteria) this;
        }

        public Criteria andPerCodeIsNull() {
            addCriterion("SPN.per_code is null");
            return (Criteria) this;
        }

        public Criteria andPerCodeIsNotNull() {
            addCriterion("SPN.per_code is not null");
            return (Criteria) this;
        }

        public Criteria andPerCodeEqualTo(String value) {
            addCriterion("SPN.per_code =", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeNotEqualTo(String value) {
            addCriterion("SPN.per_code <>", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeGreaterThan(String value) {
            addCriterion("SPN.per_code >", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeGreaterThanOrEqualTo(String value) {
            addCriterion("SPN.per_code >=", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeLessThan(String value) {
            addCriterion("SPN.per_code <", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeLessThanOrEqualTo(String value) {
            addCriterion("SPN.per_code <=", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeLike(String value) {
            addCriterion("SPN.per_code like", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeNotLike(String value) {
            addCriterion("SPN.per_code not like", value, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeIn(List<String> values) {
            addCriterion("SPN.per_code in", values, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeNotIn(List<String> values) {
            addCriterion("SPN.per_code not in", values, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeBetween(String value1, String value2) {
            addCriterion("SPN.per_code between", value1, value2, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerCodeNotBetween(String value1, String value2) {
            addCriterion("SPN.per_code not between", value1, value2, "perCode");
            return (Criteria) this;
        }

        public Criteria andPerUrlIsNull() {
            addCriterion("SPN.per_url is null");
            return (Criteria) this;
        }

        public Criteria andPerUrlIsNotNull() {
            addCriterion("SPN.per_url is not null");
            return (Criteria) this;
        }

        public Criteria andPerUrlEqualTo(String value) {
            addCriterion("SPN.per_url =", value, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlNotEqualTo(String value) {
            addCriterion("SPN.per_url <>", value, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlGreaterThan(String value) {
            addCriterion("SPN.per_url >", value, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlGreaterThanOrEqualTo(String value) {
            addCriterion("SPN.per_url >=", value, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlLessThan(String value) {
            addCriterion("SPN.per_url <", value, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlLessThanOrEqualTo(String value) {
            addCriterion("SPN.per_url <=", value, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlLike(String value) {
            addCriterion("SPN.per_url like", value, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlNotLike(String value) {
            addCriterion("SPN.per_url not like", value, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlIn(List<String> values) {
            addCriterion("SPN.per_url in", values, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlNotIn(List<String> values) {
            addCriterion("SPN.per_url not in", values, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlBetween(String value1, String value2) {
            addCriterion("SPN.per_url between", value1, value2, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerUrlNotBetween(String value1, String value2) {
            addCriterion("SPN.per_url not between", value1, value2, "perUrl");
            return (Criteria) this;
        }

        public Criteria andPerTypeIsNull() {
            addCriterion("SPN.per_type is null");
            return (Criteria) this;
        }

        public Criteria andPerTypeIsNotNull() {
            addCriterion("SPN.per_type is not null");
            return (Criteria) this;
        }

        public Criteria andPerTypeEqualTo(Integer value) {
            addCriterion("SPN.per_type =", value, "perType");
            return (Criteria) this;
        }

        public Criteria andPerTypeNotEqualTo(Integer value) {
            addCriterion("SPN.per_type <>", value, "perType");
            return (Criteria) this;
        }

        public Criteria andPerTypeGreaterThan(Integer value) {
            addCriterion("SPN.per_type >", value, "perType");
            return (Criteria) this;
        }

        public Criteria andPerTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("SPN.per_type >=", value, "perType");
            return (Criteria) this;
        }

        public Criteria andPerTypeLessThan(Integer value) {
            addCriterion("SPN.per_type <", value, "perType");
            return (Criteria) this;
        }

        public Criteria andPerTypeLessThanOrEqualTo(Integer value) {
            addCriterion("SPN.per_type <=", value, "perType");
            return (Criteria) this;
        }

        public Criteria andPerTypeIn(List<Integer> values) {
            addCriterion("SPN.per_type in", values, "perType");
            return (Criteria) this;
        }

        public Criteria andPerTypeNotIn(List<Integer> values) {
            addCriterion("SPN.per_type not in", values, "perType");
            return (Criteria) this;
        }

        public Criteria andPerTypeBetween(Integer value1, Integer value2) {
            addCriterion("SPN.per_type between", value1, value2, "perType");
            return (Criteria) this;
        }

        public Criteria andPerTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("SPN.per_type not between", value1, value2, "perType");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionIsNull() {
            addCriterion("SPN.per_description is null");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionIsNotNull() {
            addCriterion("SPN.per_description is not null");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionEqualTo(String value) {
            addCriterion("SPN.per_description =", value, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionNotEqualTo(String value) {
            addCriterion("SPN.per_description <>", value, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionGreaterThan(String value) {
            addCriterion("SPN.per_description >", value, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("SPN.per_description >=", value, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionLessThan(String value) {
            addCriterion("SPN.per_description <", value, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionLessThanOrEqualTo(String value) {
            addCriterion("SPN.per_description <=", value, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionLike(String value) {
            addCriterion("SPN.per_description like", value, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionNotLike(String value) {
            addCriterion("SPN.per_description not like", value, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionIn(List<String> values) {
            addCriterion("SPN.per_description in", values, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionNotIn(List<String> values) {
            addCriterion("SPN.per_description not in", values, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionBetween(String value1, String value2) {
            addCriterion("SPN.per_description between", value1, value2, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerDescriptionNotBetween(String value1, String value2) {
            addCriterion("SPN.per_description not between", value1, value2, "perDescription");
            return (Criteria) this;
        }

        public Criteria andPerStatusIsNull() {
            addCriterion("SPN.per_status is null");
            return (Criteria) this;
        }

        public Criteria andPerStatusIsNotNull() {
            addCriterion("SPN.per_status is not null");
            return (Criteria) this;
        }

        public Criteria andPerStatusEqualTo(Integer value) {
            addCriterion("SPN.per_status =", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusNotEqualTo(Integer value) {
            addCriterion("SPN.per_status <>", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusGreaterThan(Integer value) {
            addCriterion("SPN.per_status >", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("SPN.per_status >=", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusLessThan(Integer value) {
            addCriterion("SPN.per_status <", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusLessThanOrEqualTo(Integer value) {
            addCriterion("SPN.per_status <=", value, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusIn(List<Integer> values) {
            addCriterion("SPN.per_status in", values, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusNotIn(List<Integer> values) {
            addCriterion("SPN.per_status not in", values, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusBetween(Integer value1, Integer value2) {
            addCriterion("SPN.per_status between", value1, value2, "perStatus");
            return (Criteria) this;
        }

        public Criteria andPerStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("SPN.per_status not between", value1, value2, "perStatus");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("SPN.create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("SPN.create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("SPN.create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("SPN.create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("SPN.create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SPN.create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("SPN.create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("SPN.create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("SPN.create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("SPN.create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("SPN.create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("SPN.create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("SPN.update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("SPN.update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("SPN.update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("SPN.update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("SPN.update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("SPN.update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("SPN.update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("SPN.update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("SPN.update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("SPN.update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("SPN.update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("SPN.update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_permission
     *
     * @mbggenerated do_not_delete_during_merge Wed Mar 25 11:35:19 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_permission
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}