package com.zycj.tcc.domain;

import java.util.Date;

public class SysPermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.parent_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String perName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_code
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String perCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_url
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String perUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer perType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_description
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String perDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.per_status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer perStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_permission.update_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.id
     *
     * @return the value of sys_permission.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.id
     *
     * @param id the value for sys_permission.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.parent_id
     *
     * @return the value of sys_permission.parent_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.parent_id
     *
     * @param parentId the value for sys_permission.parent_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_name
     *
     * @return the value of sys_permission.per_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getPerName() {
        return perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_name
     *
     * @param perName the value for sys_permission.per_name
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setPerName(String perName) {
        this.perName = perName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_code
     *
     * @return the value of sys_permission.per_code
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getPerCode() {
        return perCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_code
     *
     * @param perCode the value for sys_permission.per_code
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setPerCode(String perCode) {
        this.perCode = perCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_url
     *
     * @return the value of sys_permission.per_url
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getPerUrl() {
        return perUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_url
     *
     * @param perUrl the value for sys_permission.per_url
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setPerUrl(String perUrl) {
        this.perUrl = perUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_type
     *
     * @return the value of sys_permission.per_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getPerType() {
        return perType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_type
     *
     * @param perType the value for sys_permission.per_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setPerType(Integer perType) {
        this.perType = perType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_description
     *
     * @return the value of sys_permission.per_description
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getPerDescription() {
        return perDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_description
     *
     * @param perDescription the value for sys_permission.per_description
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setPerDescription(String perDescription) {
        this.perDescription = perDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.per_status
     *
     * @return the value of sys_permission.per_status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getPerStatus() {
        return perStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.per_status
     *
     * @param perStatus the value for sys_permission.per_status
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setPerStatus(Integer perStatus) {
        this.perStatus = perStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.create_time
     *
     * @return the value of sys_permission.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.create_time
     *
     * @param createTime the value for sys_permission.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_permission.update_time
     *
     * @return the value of sys_permission.update_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_permission.update_time
     *
     * @param updateTime the value for sys_permission.update_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}