package com.zycj.tcc.domain;

public class SysRolePermission {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.role_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role_permission.per_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer perId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.id
     *
     * @return the value of sys_role_permission.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.id
     *
     * @param id the value for sys_role_permission.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.role_id
     *
     * @return the value of sys_role_permission.role_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.role_id
     *
     * @param roleId the value for sys_role_permission.role_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role_permission.per_id
     *
     * @return the value of sys_role_permission.per_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getPerId() {
        return perId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role_permission.per_id
     *
     * @param perId the value for sys_role_permission.per_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setPerId(Integer perId) {
        this.perId = perId;
    }
}