package com.zycj.tcc.domain;

import java.util.Date;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.id
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.mobile
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.password
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.name
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.car_no
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	private String carNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.machine_no
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	private String machineNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.status
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.create_time
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column user.modify_time
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	private Date modifyTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.id
	 * @return  the value of user.id
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.id
	 * @param id  the value for user.id
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.mobile
	 * @return  the value of user.mobile
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.mobile
	 * @param mobile  the value for user.mobile
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.password
	 * @return  the value of user.password
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.password
	 * @param password  the value for user.password
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.name
	 * @return  the value of user.name
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.name
	 * @param name  the value for user.name
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.car_no
	 * @return  the value of user.car_no
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public String getCarNo() {
		return carNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.car_no
	 * @param carNo  the value for user.car_no
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public void setCarNo(String carNo) {
		this.carNo = carNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.machine_no
	 * @return  the value of user.machine_no
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public String getMachineNo() {
		return machineNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.machine_no
	 * @param machineNo  the value for user.machine_no
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public void setMachineNo(String machineNo) {
		this.machineNo = machineNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.status
	 * @return  the value of user.status
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.status
	 * @param status  the value for user.status
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.create_time
	 * @return  the value of user.create_time
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.create_time
	 * @param createTime  the value for user.create_time
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column user.modify_time
	 * @return  the value of user.modify_time
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public Date getModifyTime() {
		return modifyTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column user.modify_time
	 * @param modifyTime  the value for user.modify_time
	 * @mbggenerated  Fri Apr 10 14:44:01 CST 2015
	 */
	public void setModifyTime(Date modifyTime) {
		this.modifyTime = modifyTime;
	}
}