package com.zycj.tcc.domain;

import java.util.Date;

public class UserLogin {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.id
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.mobile
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.user_id
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.token
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.login_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private Date loginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.active_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private Date activeTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.is_active
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private Integer isActive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.login_from
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private Integer loginFrom;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.ip
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.logout_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private Date logoutTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.create_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login.modify_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.id
     *
     * @return the value of user_login.id
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.id
     *
     * @param id the value for user_login.id
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.mobile
     *
     * @return the value of user_login.mobile
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.mobile
     *
     * @param mobile the value for user_login.mobile
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.user_id
     *
     * @return the value of user_login.user_id
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.user_id
     *
     * @param userId the value for user_login.user_id
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.token
     *
     * @return the value of user_login.token
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.token
     *
     * @param token the value for user_login.token
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setToken(String token) {
        this.token = token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.login_time
     *
     * @return the value of user_login.login_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public Date getLoginTime() {
        return loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.login_time
     *
     * @param loginTime the value for user_login.login_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.active_time
     *
     * @return the value of user_login.active_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public Date getActiveTime() {
        return activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.active_time
     *
     * @param activeTime the value for user_login.active_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setActiveTime(Date activeTime) {
        this.activeTime = activeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.is_active
     *
     * @return the value of user_login.is_active
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public Integer getIsActive() {
        return isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.is_active
     *
     * @param isActive the value for user_login.is_active
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setIsActive(Integer isActive) {
        this.isActive = isActive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.login_from
     *
     * @return the value of user_login.login_from
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public Integer getLoginFrom() {
        return loginFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.login_from
     *
     * @param loginFrom the value for user_login.login_from
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setLoginFrom(Integer loginFrom) {
        this.loginFrom = loginFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.ip
     *
     * @return the value of user_login.ip
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.ip
     *
     * @param ip the value for user_login.ip
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.logout_time
     *
     * @return the value of user_login.logout_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public Date getLogoutTime() {
        return logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.logout_time
     *
     * @param logoutTime the value for user_login.logout_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setLogoutTime(Date logoutTime) {
        this.logoutTime = logoutTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.create_time
     *
     * @return the value of user_login.create_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.create_time
     *
     * @param createTime the value for user_login.create_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login.modify_time
     *
     * @return the value of user_login.modify_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login.modify_time
     *
     * @param modifyTime the value for user_login.modify_time
     *
     * @mbggenerated Fri Apr 10 17:27:44 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}