package com.zycj.tcc.domain;

import java.util.Date;

public class UserFeedback {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.user_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.content
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.contact
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String contact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.ip
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.machine_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private String machineType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_feedback.modify_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.id
     *
     * @return the value of user_feedback.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.id
     *
     * @param id the value for user_feedback.id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.user_id
     *
     * @return the value of user_feedback.user_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.user_id
     *
     * @param userId the value for user_feedback.user_id
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.content
     *
     * @return the value of user_feedback.content
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.content
     *
     * @param content the value for user_feedback.content
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.contact
     *
     * @return the value of user_feedback.contact
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.contact
     *
     * @param contact the value for user_feedback.contact
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.ip
     *
     * @return the value of user_feedback.ip
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.ip
     *
     * @param ip the value for user_feedback.ip
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.machine_type
     *
     * @return the value of user_feedback.machine_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public String getMachineType() {
        return machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.machine_type
     *
     * @param machineType the value for user_feedback.machine_type
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setMachineType(String machineType) {
        this.machineType = machineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.create_time
     *
     * @return the value of user_feedback.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.create_time
     *
     * @param createTime the value for user_feedback.create_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_feedback.modify_time
     *
     * @return the value of user_feedback.modify_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_feedback.modify_time
     *
     * @param modifyTime the value for user_feedback.modify_time
     *
     * @mbggenerated Wed Mar 25 11:35:19 CST 2015
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}